create sequence users_id_seq start 10 increment 1;
create sequence maintenance_id_seq start 10 increment 1;
create sequence pass_id_seq start 10 increment 1;
create sequence space_seq start 10 increment 1;
create table user_role
(
    user_id int8 not null,
    roles   varchar(255)
);

create table users
(
    id                  int8 generated by default as identity,
    activation_code     varchar(255),
    active              boolean not null,
    address             varchar(255),
    city                varchar(255),
    email               varchar(255),
    first_name          varchar(255),
    last_name           varchar(255),
    password            varchar(255),
    password_reset_code varchar(255),
    phone_number        varchar(255),
    post_index          varchar(255),
    provider            varchar(255),
    primary key (id)
);

alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users;

CREATE TABLE SPACE_TYPE
(
    space_type_id      integer,
    space_type_libelle varchar(100),
    PRIMARY KEY (space_type_id)
);


CREATE TABLE SPACE
(
    space_id          integer,
    space_name        varchar(100),
    space_description text,
    space_capacity    integer,
    opening_time time,
    closing_time time,
    handicappedAcces  boolean,
    space_type_id     integer,
    PRIMARY KEY (space_id),
    FOREIGN KEY (space_type_id) REFERENCES SPACE_TYPE (space_type_id)
);

CREATE TABLE MAINTENANCE
(
    maintenance_id  integer,
    date_hour_start timestamp,
    date_hour_end   timestamp,
    space_id        integer,
    manager_id      integer,
    PRIMARY KEY (maintenance_id),
    FOREIGN KEY (space_id) REFERENCES SPACE (space_id),
    FOREIGN KEY (manager_id) REFERENCES users (id)
);



